[package]
name = "nitrate_execute"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_lexical = { path = "../nitrate_lexical" }
nitrate_parsetree = { path = "../nitrate_parsetree" }
nitrate_syntax = { path = "../nitrate_syntax" }
nitrate_evaluate = { path = "../nitrate_evaluate" }
