[package]
name = "nitrate_execute"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_tokenize = { path = "../nitrate_tokenize" }
nitrate_structure = { path = "../nitrate_structure" }
nitrate_parse = { path = "../nitrate_parse" }
nitrate_evaluate = { path = "../nitrate_evaluate" }
