[package]
name = "nitrate_tree_parse"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion.workspace = true

[dependencies]
nitrate_nstring.workspace = true
nitrate_token.workspace = true
nitrate_token_lexer.workspace = true
nitrate_tree.workspace = true
nitrate_diagnosis.workspace = true

log.workspace = true
ordered-float.workspace = true
spdx.workspace = true
