[package]
name = "nitrate"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
hashbrown = "0.15.4"
nitrate_compiler = { path = "compiler" }
tracking-allocator = "0.4.0"
log = "0.4.27"
smallvec = "1.15.1"
stackvector = "1.1.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[workspace]
members = ["compiler"]

[[bin]]
name = "nitc"
path = "nitc/src/main.rs"
