[package]
name = "nitrate"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
nitrate_lexer = { path = "compiler/lexer" }
nitrate_parser = { path = "compiler/parser" }
tracing-allocator = "0.1.0"
tracking-allocator = "0.4.0"

[workspace]
members = ["compiler/lexer", "compiler/parser"]


[[bin]]
name = "no3"
path = "no3/src/main.rs"

[[bin]]
name = "nitc"
path = "nitc/src/main.rs"
