[package]
name = "nitrate"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_lexer = { path = "compiler/lexer" }
nitrate_parser = { path = "compiler/parser" }

[workspace]
members = [
  "compiler/lexer",
  "compiler/lexer/tools/nitrate-lexer-stdin",
  "compiler/parser",
]


[[bin]]
name = "no3"
path = "no3/src/main.rs"

[[bin]]
name = "nitc"
path = "nitc/src/main.rs"
