[package]
name = "nitrate_tree_resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_token.workspace = true
nitrate_token_lexer.workspace = true
nitrate_tree.workspace = true
nitrate_tree_parse.workspace = true
nitrate_diagnosis.workspace = true

log.workspace = true
