[package]
name = "nitrate_parsetree"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_lexical = { path = "../nitrate_lexical" }

apint = "0.2.0"
hashbrown = "0.16.0"
log = "0.4.27"
ordered-float = "5.0.0"
smallvec = "1.15.1"
