// Mock application for testing the runo3 runtime.
// In reality, the runo3_ functions would be written in Nitrate Language, and
// the nlr_ctors would be generated by the Nitrate compiler/linker.

#include <stdint.h>
#include <unistd.h>

static void ctor_a() { syscall(1, 1, "Hello, ctor_a!\n", 15); }
static void ctor_b() { syscall(1, 1, "Hello, ctor_b!\n", 15); }

typedef void (*ctor_fn)();

static ctor_fn nlr_ctors[] = {ctor_a, ctor_b};

ctor_fn *nlr_ctors_start = &nlr_ctors[0];
ctor_fn *nlr_ctors_end = &nlr_ctors[2];

void runo3_pre_ctors() {}
void runo3_post_ctors() {}

int _Q3app4mainFimPPhPPhE_0(uint64_t argc, uint8_t **argv, uint8_t **envp) {
  syscall(1, 1, "Hello, from the actual main()!\n", 31);

  return 0;
}

int runo3_main(int argc, char **argv, char **envp) {
  /* app::main : fn (_0: u64, _1: **u8, _2: **u8): i32 */
  return _Q3app4mainFimPPhPPhE_0(argc, (uint8_t **)argv, (uint8_t **)envp);
}
