[package]
name = "nitrate_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_token.workspace = true
nitrate_diagnosis.workspace = true

ordered-float.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
once_cell.workspace = true
bimap.workspace = true
serde_with.workspace = true
