[package]
name = "nitrate_hir"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
blake3.workspace = true
bimap.workspace = true
append-only-vec.workspace = true
thin-vec = { workspace = true, features = ["serde"] }
thin_str = { workspace = true, features = ["serde", "serde_support"] }
ordered-float.workspace = true
nitrate_token.workspace = true
internal-iterator.workspace = true
