[package]
name = "nitrate_translation"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_diagnosis.workspace = true
nitrate_nstring.workspace = true
nitrate_token.workspace = true
nitrate_token_lexer.workspace = true
nitrate_tree.workspace = true
nitrate_tree_parse.workspace = true
nitrate_tree_resolve.workspace = true
nitrate_hir_from_tree.workspace = true
nitrate_hir.workspace = true
nitrate_hir_borrow_check.workspace = true
nitrate_hir_optimize.workspace = true
nitrate_hir_dump.workspace = true
nitrate_hir_validate.workspace = true
nitrate_hir_evaluate.workspace = true
nitrate_hir_solve.workspace = true
nitrate_hir_get_type.workspace = true
nitrate_hir_mangle.workspace = true
nitrate_llvm.workspace = true
nitrate_llvm_from_hir.workspace = true
nitrate_mir.workspace = true
nitrate_mir_optimize.workspace = true
nitrate_mir_from_hir.workspace = true
nitrate_llvm_from_mir.workspace = true
nitrate_optimization.workspace = true
serde_json.workspace = true
thiserror.workspace = true
threadpool_scope.workspace = true
threadpool.workspace = true
