[package]
name = "nitrate_tree_parse2"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_diagnosis.workspace = true

nitrate_token.workspace = true
nitrate_token_lexer.workspace = true

nitrate_tree2.workspace = true

log.workspace = true
ordered-float.workspace = true
spdx.workspace = true
