[package]
name = "nitrate_tree_parse2"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring = { path = "../nstring" }
nitrate_diagnosis = { path = "../../../diagnosis" }

nitrate_token = { path = "../token" }
nitrate_token_lexer = { path = "../token_lexer" }

nitrate_tree2 = { path = "../tree2" }

log = "0.4.27"
ordered-float = "5.0.0"
spdx = "0.12.0"
