[package]
name = "nitrate_hir_from_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_diagnosis.workspace = true

nitrate_token_lexer.workspace = true
nitrate_token.workspace = true

nitrate_tree.workspace = true
nitrate_tree_resolve.workspace = true
nitrate_tree_parse.workspace = true

nitrate_hir.workspace = true
nitrate_hir_borrow_check.workspace = true
nitrate_hir_evaluate.workspace = true
nitrate_hir_get_type.workspace = true
nitrate_hir_mangle.workspace = true
nitrate_hir_solve.workspace = true

ordered-float.workspace = true
thin-vec.workspace = true

serde_json = { workspace = true, features = ["preserve_order"] }
