[package]
name = "nitrate_tree2"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_diagnosis.workspace = true

nitrate_token.workspace = true
nitrate_token_lexer.workspace = true

ordered-float.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
append-only-vec.workspace = true
thin-vec = { workspace = true, features = ["serde"] }
bitflags.workspace = true
