[package]
name = "nitrate_hir_solve"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_hir.workspace = true
nitrate_tree.workspace = true
nitrate_diagnosis.workspace = true
nitrate_hir_type.workspace = true
nitrate_hir_evaluate.workspace = true
nitrate_hir_dump.workspace = true
nitrate_nstring.workspace = true
thin-vec.workspace = true
smallvec.workspace = true

ordered-float.workspace = true
