[package]
name = "nitrate_token_lexer"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "lex_bench"
harness = false

[[bench]]
name = "throughput_bench"
harness = false

[dependencies]
nitrate_diagnosis.workspace = true
nitrate_token.workspace = true
log.workspace = true
ordered-float.workspace = true
