#!/usr/bin/env python3

import sys
import os
import glob
import datetime

if len(sys.argv) < 3:
    print("Usage: python CodeWriter_CreateTests.py <tree_dir> <output_dir>")
    sys.exit(1)

tree_dir = sys.argv[1]
output_dir = sys.argv[2]

# Print each subdirectory with depth 1
for subdir in glob.glob(os.path.join(tree_dir, "*")):
    domain = os.path.basename(subdir).capitalize()
    if domain != "Minified":
        continue

    unit_test_source_file = os.path.abspath(
        os.path.join(output_dir, f"CodeWriter.gen.cc"))

    with open(unit_test_source_file, "w") as f:
        f.write("//=================================================//\n")
        f.write("// This file is automatically generated.           //\n")
        f.write("// Do not edit this file.                          //\n")
        f.write("// Generated by CodeWriter_CreateTests.py           //\n")
        f.write("// Date: {}                //\n".format(datetime.datetime.now()))
        f.write("//=================================================//\n\n")

        f.write("#include <gtest/gtest.h>\n\n")

        f.write("#include <boost/iostreams/device/array.hpp>\n")
        f.write("#include <boost/iostreams/stream.hpp>\n")
        f.write("#include <nitrate-core/Allocate.hh>\n")
        f.write("#include <nitrate-core/Environment.hh>\n")
        f.write("#include <nitrate-lexer/Lexer.hh>\n")
        f.write("#include <nitrate-parser/ASTBase.hh>\n")
        f.write("#include <nitrate-parser/ASTReader.hh>\n")
        f.write("#include <nitrate-parser/CodeWriter.hh>\n")
        f.write("#include <nitrate-parser/Context.hh>\n")
        f.write("#include <nitrate-parser/Init.hh>\n")
        f.write("#include <string_view>\n")
        f.write("\n")
        f.write("using namespace ncc;\n")
        f.write("using namespace ncc::lex;\n")
        f.write("using namespace ncc::parse;\n\n")

        f.write("static constexpr auto kFmt = ASTReader::Format::JSON;\n\n")

        f.write("""[[maybe_unused]] static void TestCase(std::string_view source, std::string_view expect) {
  auto lib_rc = ncc::parse::ParseLibrary.GetRC();
  ASSERT_TRUE(lib_rc) << "Failed to initialize library";

  auto mm = DynamicArena();
  auto ast = ASTReader(source, kFmt, mm).Get();
  ASSERT_TRUE(ast) << "Failed to deserialize AST";

  std::stringstream ss;
  auto writer = CodeWriterFactory::Create(ss);
  ast.Unwrap()->Accept(*writer);

  EXPECT_EQ(ss.str(), expect) << "CodeWriter output does not match expected output";
}
""")

        for test_group in os.listdir(subdir):
            test_group_path = os.path.join(subdir, test_group)
            if not os.path.isdir(test_group_path):
                continue

            test_group_name = test_group.removeprefix("AST_")

            for source_file in glob.glob(f"{test_group_path}/*.nit"):
                test_identity = os.path.basename(
                    source_file).replace(".nit", "")
                is_negative_test = test_identity.startswith("e_")
                if is_negative_test:
                    continue

                expected_file = source_file.replace(".nit", ".json")

                f.write(
                    f"\nTEST(Parser, CodeWriter_{test_group_name}_{test_identity}) {{\n")

                with open(source_file, "r") as source_f:
                    source_file_content = source_f.read()
                with open(expected_file, "r") as expected_f:
                    expected_file_content = expected_f.read()

                f.write(
                    f"  constexpr std::string_view kSource = R\"__PY(")
                f.write(expected_file_content)
                f.write(")__PY\";\n")

                f.write(
                    f"  constexpr std::string_view kExpect = R\"__PY(")
                f.write(source_file_content)
                f.write(")__PY\";\n\n")

                f.write(
                    f"  TestCase(kSource, kExpect);\n")

                f.write("}\n")
