[package]
name = "nitrate_llvm_from_hir"
version = "0.1.0"
edition = "2024"

[dependencies]
nitrate_nstring.workspace = true
nitrate_llvm.workspace = true
nitrate_hir.workspace = true
nitrate_hir_validate.workspace = true
nitrate_hir_mangle.workspace = true
nitrate_hir_get_type.workspace = true
inkwell.workspace = true
thin-vec.workspace = true

[build-dependencies]
cc.workspace = true
