#include <gtest/gtest.h>

#include <pipeline/libnitrate-lexer/LexicalCase.hh>

using namespace ncc::lex;

#pragma clang optimize off

///============================================================================///
/// BUILTIN OPERATORS
TEST_CASE(Operator, Symbol, 0, "+", {OpPlus});
TEST_CASE(Operator, Symbol, 1, "-", {OpMinus});
TEST_CASE(Operator, Symbol, 2, "*", {OpTimes});
TEST_CASE(Operator, Symbol, 3, "/", {OpSlash});
TEST_CASE(Operator, Symbol, 4, "%", {OpPercent});
TEST_CASE(Operator, Symbol, 5, "&", {OpBitAnd});
TEST_CASE(Operator, Symbol, 6, "|", {OpBitOr});
TEST_CASE(Operator, Symbol, 7, "^", {OpBitXor});
TEST_CASE(Operator, Symbol, 8, "~", {OpBitNot});
TEST_CASE(Operator, Symbol, 9, "<<", {OpLShift});
TEST_CASE(Operator, Symbol, 10, ">>", {OpRShift});
TEST_CASE(Operator, Symbol, 12, "<<<", {OpROTL});
TEST_CASE(Operator, Symbol, 13, ">>>", {OpROTR});
TEST_CASE(Operator, Symbol, 14, "&&", {OpLogicAnd});
TEST_CASE(Operator, Symbol, 15, "||", {OpLogicOr});
TEST_CASE(Operator, Symbol, 16, "^^", {OpLogicXor});
TEST_CASE(Operator, Symbol, 17, "!", {OpLogicNot});
TEST_CASE(Operator, Symbol, 18, "<", {OpLT});
TEST_CASE(Operator, Symbol, 19, ">", {OpGT});
TEST_CASE(Operator, Symbol, 20, "<=", {OpLE});
TEST_CASE(Operator, Symbol, 21, ">=", {OpGE});
TEST_CASE(Operator, Symbol, 22, "==", {OpEq});
TEST_CASE(Operator, Symbol, 23, "!=", {OpNE});
TEST_CASE(Operator, Symbol, 24, "=", {OpSet});
TEST_CASE(Operator, Symbol, 25, "+=", {OpPlusSet});
TEST_CASE(Operator, Symbol, 26, "-=", {OpMinusSet});
TEST_CASE(Operator, Symbol, 27, "*=", {OpTimesSet});
TEST_CASE(Operator, Symbol, 28, "/=", {OpSlashSet});
TEST_CASE(Operator, Symbol, 29, "%=", {OpPercentSet});
TEST_CASE(Operator, Symbol, 30, "&=", {OpBitAndSet});
TEST_CASE(Operator, Symbol, 31, "|=", {OpBitOrSet});
TEST_CASE(Operator, Symbol, 32, "^=", {OpBitXorSet});
TEST_CASE(Operator, Symbol, 33, "&&=", {OpLogicAndSet});
TEST_CASE(Operator, Symbol, 34, "||=", {OpLogicOrSet});
TEST_CASE(Operator, Symbol, 35, "^^=", {OpLogicXorSet});
TEST_CASE(Operator, Symbol, 36, "<<=", {OpLShiftSet});
TEST_CASE(Operator, Symbol, 37, ">>=", {OpRShiftSet});
TEST_CASE(Operator, Symbol, 38, "<<<=", {OpROTLSet});
TEST_CASE(Operator, Symbol, 39, ">>>=", {OpROTRSet});
TEST_CASE(Operator, Symbol, 40, "++", {OpInc});
TEST_CASE(Operator, Symbol, 41, "--", {OpDec});
TEST_CASE(Operator, Symbol, 42, "as", {OpAs});
TEST_CASE(Operator, Symbol, 43, "bitcast_as", {OpBitcastAs});
TEST_CASE(Operator, Symbol, 44, "in", {OpIn});
TEST_CASE(Operator, Symbol, 45, "out", {OpOut});
TEST_CASE(Operator, Symbol, 46, "sizeof", {OpSizeof});
TEST_CASE(Operator, Symbol, 47, "bitsizeof", {OpBitsizeof});
TEST_CASE(Operator, Symbol, 48, "alignof", {OpAlignof});
TEST_CASE(Operator, Symbol, 49, "typeof", {OpTypeof});
TEST_CASE(Operator, Symbol, 50, "comptime", {OpComptime});
TEST_CASE(Operator, Symbol, 51, ".", {OpDot});
TEST_CASE(Operator, Symbol, 52, "..", {OpRange});
TEST_CASE(Operator, Symbol, 53, "...", {OpEllipsis});
TEST_CASE(Operator, Symbol, 54, "=>", {OpArrow});
TEST_CASE(Operator, Symbol, 55, "?", {OpTernary});

///============================================================================///
/// ADJACENT OPERATORS
TEST_CASE(Operator, Adjacent, 0, "++", {OpInc});
TEST_CASE(Operator, Adjacent, 1, "--", {OpDec});
TEST_CASE(Operator, Adjacent, 2, "**", {OpTimes, OpTimes});
TEST_CASE(Operator, Adjacent, 3, "//", {Token(Note, "")});
TEST_CASE(Operator, Adjacent, 4, "%%", {OpPercent, OpPercent});
TEST_CASE(Operator, Adjacent, 5, "&&", {OpLogicAnd});
TEST_CASE(Operator, Adjacent, 6, "||", {OpLogicOr});
TEST_CASE(Operator, Adjacent, 7, "^^", {OpLogicXor});
TEST_CASE(Operator, Adjacent, 8, "~~", {OpBitNot, OpBitNot});
TEST_CASE(Operator, Adjacent, 9, "<<<<", {OpROTL, OpLT});
TEST_CASE(Operator, Adjacent, 10, ">>>>", {OpROTR, OpGT});
TEST_CASE(Operator, Adjacent, 12, "<<<<<<", {OpROTL, OpROTL});
TEST_CASE(Operator, Adjacent, 13, ">>>>>>", {OpROTR, OpROTR});
TEST_CASE(Operator, Adjacent, 14, "&&&&", {OpLogicAnd, OpLogicAnd});
TEST_CASE(Operator, Adjacent, 15, "||||", {OpLogicOr, OpLogicOr});
TEST_CASE(Operator, Adjacent, 16, "^^^^", {OpLogicXor, OpLogicXor});
TEST_CASE(Operator, Adjacent, 17, "!!", {OpLogicNot, OpLogicNot});
TEST_CASE(Operator, Adjacent, 18, "<<", {OpLShift});
TEST_CASE(Operator, Adjacent, 19, ">>", {OpRShift});
TEST_CASE(Operator, Adjacent, 20, "<=<=", {OpLE, OpLE});
TEST_CASE(Operator, Adjacent, 21, ">=>=", {OpGE, OpGE});
TEST_CASE(Operator, Adjacent, 22, "====", {OpEq, OpEq});
TEST_CASE(Operator, Adjacent, 23, "!=!=", {OpNE, OpNE});
TEST_CASE(Operator, Adjacent, 24, "==", {OpEq});
TEST_CASE(Operator, Adjacent, 25, "+=+=", {OpPlusSet, OpPlusSet});
TEST_CASE(Operator, Adjacent, 26, "-=-=", {OpMinusSet, OpMinusSet});
TEST_CASE(Operator, Adjacent, 27, "*=*=", {OpTimesSet, OpTimesSet});
TEST_CASE(Operator, Adjacent, 28, "/=/=", {OpSlashSet, OpSlashSet});
TEST_CASE(Operator, Adjacent, 29, "%=%=", {OpPercentSet, OpPercentSet});
TEST_CASE(Operator, Adjacent, 30, "&=&=", {OpBitAndSet, OpBitAndSet});
TEST_CASE(Operator, Adjacent, 31, "|=|=", {OpBitOrSet, OpBitOrSet});
TEST_CASE(Operator, Adjacent, 32, "^=^=", {OpBitXorSet, OpBitXorSet});
TEST_CASE(Operator, Adjacent, 33, "&&=&&=", {OpLogicAndSet, OpLogicAndSet});
TEST_CASE(Operator, Adjacent, 34, "||=||=", {OpLogicOrSet, OpLogicOrSet});
TEST_CASE(Operator, Adjacent, 35, "^^=^^=", {OpLogicXorSet, OpLogicXorSet});
TEST_CASE(Operator, Adjacent, 36, "<<=<<=", {OpLShiftSet, OpLShiftSet});
TEST_CASE(Operator, Adjacent, 37, ">>=>>=", {OpRShiftSet, OpRShiftSet});
TEST_CASE(Operator, Adjacent, 38, "<<<=<<<=", {OpROTLSet, OpROTLSet});
TEST_CASE(Operator, Adjacent, 39, ">>>=>>>=", {OpROTRSet, OpROTRSet});
TEST_CASE(Operator, Adjacent, 40, "++++", {OpInc, OpInc});
TEST_CASE(Operator, Adjacent, 41, "----", {OpDec, OpDec});
TEST_CASE(Operator, Adjacent, 42, "asas", {Token(Name, "asas")});
TEST_CASE(Operator, Adjacent, 43, "bitcast_asbitcast_as", {Token(Name, "bitcast_asbitcast_as")});
TEST_CASE(Operator, Adjacent, 44, "inin", {Token(Name, "inin")});
TEST_CASE(Operator, Adjacent, 45, "outout", {Token(Name, "outout")});
TEST_CASE(Operator, Adjacent, 46, "sizeofsizeof", {Token(Name, "sizeofsizeof")});
TEST_CASE(Operator, Adjacent, 47, "bitsizeofbitsizeof", {Token(Name, "bitsizeofbitsizeof")});
TEST_CASE(Operator, Adjacent, 48, "alignofalignof", {Token(Name, "alignofalignof")});
TEST_CASE(Operator, Adjacent, 49, "typeoftypeof", {Token(Name, "typeoftypeof")});
TEST_CASE(Operator, Adjacent, 50, "comptimecomptime", {Token(Name, "comptimecomptime")});
TEST_CASE(Operator, Adjacent, 51, "..", {OpRange});
TEST_CASE(Operator, Adjacent, 52, "....", {OpEllipsis, OpDot});
TEST_CASE(Operator, Adjacent, 53, "......", {OpEllipsis, OpEllipsis});
TEST_CASE(Operator, Adjacent, 54, "=>=>", {OpArrow, OpArrow});
TEST_CASE(Operator, Adjacent, 55, "??", {OpTernary, OpTernary});

///============================================================================///
/// OPERATOR PERMUTATIONS
TEST_CASE(Operator, Permute, 0, R"(.->*=)", {OpDot, OpMinus, OpGT, OpTimesSet});
TEST_CASE(Operator, Permute, 1, R"(&>>>=<=..)", {OpBitAnd, OpROTRSet, OpLE, OpRange});
TEST_CASE(Operator, Permute, 2, R"(=/&&<<=)", {OpSet, OpSlash, OpLogicAnd, OpLShiftSet});
TEST_CASE(Operator, Permute, 3, R"(<<<=/<<<..)", {OpROTLSet, OpSlash, OpROTL, OpRange});
TEST_CASE(Operator, Permute, 4, R"(>>=|=><<=)", {OpRShiftSet, OpBitOrSet, OpGT, OpLShiftSet});
TEST_CASE(Operator, Permute, 5, R"(&&>>>..%)", {OpLogicAnd, OpROTR, OpRange, OpPercent});
TEST_CASE(Operator, Permute, 6, R"(|<<%==)", {OpBitOr, OpLShift, OpPercentSet, OpSet});
TEST_CASE(Operator, Permute, 7, R"(^^=<<<=.<<<)", {OpLogicXorSet, OpROTLSet, OpDot, OpROTL});
TEST_CASE(Operator, Permute, 8, R"(>=&&=^^--)", {OpGE, OpLogicAndSet, OpLogicXor, OpDec});
TEST_CASE(Operator, Permute, 9, R"(<<|=^^=)", {OpLShift, OpBitOrSet, OpLogicXorSet});
TEST_CASE(Operator, Permute, 10, R"(||=/^^=!=)", {OpLogicOrSet, OpSlash, OpLogicXorSet, OpNE});
TEST_CASE(Operator, Permute, 11, R"(>=.....&&=)", {OpGE, OpEllipsis, OpRange, OpLogicAndSet});
TEST_CASE(Operator, Permute, 12, R"(|>>=<=>=)", {OpBitOr, OpRShiftSet, OpLE, OpGE});
TEST_CASE(Operator, Permute, 13, R"(<<=*|++)", {OpLShiftSet, OpTimes, OpBitOr, OpInc});
TEST_CASE(Operator, Permute, 14, R"(++<<^^~)", {OpInc, OpLShift, OpLogicXor, OpBitNot});
TEST_CASE(Operator, Permute, 15, R"(<<<&&!=*=)", {OpROTL, OpLogicAnd, OpNE, OpTimesSet});
TEST_CASE(Operator, Permute, 16, R"(^!===%=)", {OpBitXor, OpNE, OpEq, OpPercentSet});
TEST_CASE(Operator, Permute, 17, R"(^>=<<=?)", {OpBitXor, OpGE, OpLShiftSet, OpTernary});
TEST_CASE(Operator, Permute, 18, R"(.<<^=)", {OpDot, OpLShift, OpBitXorSet});
TEST_CASE(Operator, Permute, 19, R"(^^?-!=)", {OpLogicXor, OpTernary, OpMinus, OpNE});
TEST_CASE(Operator, Permute, 20, R"(*!=--/)", {OpTimes, OpNE, OpDec, OpSlash});
TEST_CASE(Operator, Permute, 21, R"(<>^^=<<<=)", {OpLT, OpGT, OpLogicXorSet, OpROTLSet});
TEST_CASE(Operator, Permute, 22, R"(/...^^<<=)", {OpSlash, OpEllipsis, OpLogicXor, OpLShiftSet});
TEST_CASE(Operator, Permute, 23, R"(^^=-<<<&&)", {OpLogicXorSet, OpMinus, OpROTL, OpLogicAnd});
TEST_CASE(Operator, Permute, 24, R"(||=^=<<<<)", {OpLogicOrSet, OpBitXorSet, OpROTL, OpLT});
TEST_CASE(Operator, Permute, 25, R"(-!=<<=>>>)", {OpMinus, OpNE, OpLShiftSet, OpROTR});
TEST_CASE(Operator, Permute, 26, R"(..%=&=*=)", {OpRange, OpPercentSet, OpBitAndSet, OpTimesSet});
TEST_CASE(Operator, Permute, 27, R"(|^^=&||=)", {OpBitOr, OpLogicXorSet, OpBitAnd, OpLogicOrSet});
TEST_CASE(Operator, Permute, 28, R"(!=*=~=)", {OpNE, OpTimesSet, OpBitNot, OpSet});
TEST_CASE(Operator, Permute, 29, R"(^..!~)", {OpBitXor, OpRange, OpLogicNot, OpBitNot});
TEST_CASE(Operator, Permute, 30, R"(..+%=<<)", {OpRange, OpPlus, OpPercentSet, OpLShift});
TEST_CASE(Operator, Permute, 31, R"(!./=|=)", {OpLogicNot, OpDot, OpSlashSet, OpBitOrSet});
TEST_CASE(Operator, Permute, 32, R"(||=+=<<|)", {OpLogicOrSet, OpPlusSet, OpLShift, OpBitOr});
TEST_CASE(Operator, Permute, 33, R"(++-=<<=>)", {OpInc, OpMinusSet, OpLShiftSet, OpGT});
TEST_CASE(Operator, Permute, 34, R"(^^=...%=-=)", {OpLogicXorSet, OpEllipsis, OpPercentSet, OpMinusSet});
TEST_CASE(Operator, Permute, 35, R"(||...^&)", {OpLogicOr, OpEllipsis, OpBitXor, OpBitAnd});
TEST_CASE(Operator, Permute, 36, R"(^>>--?)", {OpBitXor, OpRShift, OpDec, OpTernary});
TEST_CASE(Operator, Permute, 37, R"(...>=-=/=)", {OpEllipsis, OpGE, OpMinusSet, OpSlashSet});
TEST_CASE(Operator, Permute, 38, R"(|>=<<%)", {OpBitOr, OpGE, OpLShift, OpPercent});
TEST_CASE(Operator, Permute, 39, R"(*=./>=)", {OpTimesSet, OpDot, OpSlash, OpGE});
TEST_CASE(Operator, Permute, 40, R"(!=<<<*>=)", {OpNE, OpROTL, OpTimes, OpGE});
TEST_CASE(Operator, Permute, 41, R"(...&+=^)", {OpEllipsis, OpBitAnd, OpPlusSet, OpBitXor});
TEST_CASE(Operator, Permute, 42, R"(...&^<<)", {OpEllipsis, OpBitAnd, OpBitXor, OpLShift});
TEST_CASE(Operator, Permute, 43, R"(%&&&&=<=)", {OpPercent, OpLogicAnd, OpLogicAndSet, OpLE});
TEST_CASE(Operator, Permute, 44, R"(>>>=<<<-=||)", {OpROTRSet, OpROTL, OpMinusSet, OpLogicOr});
TEST_CASE(Operator, Permute, 45, R"(>>=<==<<<=)", {OpRShiftSet, OpLE, OpSet, OpROTLSet});
TEST_CASE(Operator, Permute, 46, R"(>>=<=*>>)", {OpRShiftSet, OpLE, OpTimes, OpRShift});
TEST_CASE(Operator, Permute, 47, R"(<^^=|&)", {OpLT, OpLogicXorSet, OpBitOr, OpBitAnd});
TEST_CASE(Operator, Permute, 48, R"(...>>>=++)", {OpEllipsis, OpROTRSet, OpInc});
TEST_CASE(Operator, Permute, 49, R"(>>=>=<<<<)", {OpRShiftSet, OpGE, OpROTL, OpLT});
TEST_CASE(Operator, Permute, 50, R"(/==++=)", {OpSlashSet, OpSet, OpInc, OpSet});
TEST_CASE(Operator, Permute, 51, R"(>>=<=~>)", {OpRShiftSet, OpLE, Token(Note, "")});
TEST_CASE(Operator, Permute, 52, R"(||=<<<!=)", {OpLogicOrSet, OpROTL, OpNE});
TEST_CASE(Operator, Permute, 53, R"(>=~>>&)", {OpGE, Token(Note, ">&")});
TEST_CASE(Operator, Permute, 54, R"(<>|=.)", {OpLT, OpGT, OpBitOrSet, OpDot});
TEST_CASE(Operator, Permute, 55, R"(^=&<|=)", {OpBitXorSet, OpBitAnd, OpLT, OpBitOrSet});
TEST_CASE(Operator, Permute, 56, R"(&&=...<)", {OpLogicAndSet, OpEllipsis, OpLT});
TEST_CASE(Operator, Permute, 57, R"(=?^=++)", {OpSet, OpTernary, OpBitXorSet, OpInc});
TEST_CASE(Operator, Permute, 58, R"(&=+<=>>)", {OpBitAndSet, OpPlus, OpLE, OpRShift});
TEST_CASE(Operator, Permute, 59, R"(.~<<<|=)", {OpDot, OpBitNot, OpROTL, OpBitOrSet});
TEST_CASE(Operator, Permute, 60, R"(/>=&=|)", {OpSlash, OpGE, OpBitAndSet, OpBitOr});
TEST_CASE(Operator, Permute, 61, R"(*<=^--)", {OpTimes, OpLE, OpBitXor, OpDec});
TEST_CASE(Operator, Permute, 62, R"(|||=-=)", {OpLogicOr, OpBitOrSet, OpMinusSet});
TEST_CASE(Operator, Permute, 63, R"(==>>=||=<<<=)", {OpEq, OpRShiftSet, OpLogicOrSet, OpROTLSet});
TEST_CASE(Operator, Permute, 64, R"(<<++>=|=)", {OpLShift, OpInc, OpGE, OpBitOrSet});
TEST_CASE(Operator, Permute, 65, R"(+--!-)", {OpPlus, OpDec, OpLogicNot, OpMinus});
TEST_CASE(Operator, Permute, 66, R"(?...&=++)", {OpTernary, OpEllipsis, OpBitAndSet, OpInc});
TEST_CASE(Operator, Permute, 67, R"(<<<%-=>=)", {OpROTL, OpPercent, OpMinusSet, OpGE});
TEST_CASE(Operator, Permute, 68, R"(-=--...&&=)", {OpMinusSet, OpDec, OpEllipsis, OpLogicAndSet});
TEST_CASE(Operator, Permute, 69, R"(||=>=<=...)", {OpLogicOrSet, OpGE, OpLE, OpEllipsis});
TEST_CASE(Operator, Permute, 70, R"(.=>>=>>>=)", {OpDot, OpArrow, OpGE, OpROTRSet});
TEST_CASE(Operator, Permute, 71, R"(+===&&=^)", {OpPlusSet, OpEq, OpLogicAndSet, OpBitXor});
TEST_CASE(Operator, Permute, 72, R"(^=--&&=+=)", {OpBitXorSet, OpDec, OpLogicAndSet, OpPlusSet});
TEST_CASE(Operator, Permute, 73, R"(==%..*=)", {OpEq, OpPercent, OpRange, OpTimesSet});
TEST_CASE(Operator, Permute, 74, R"(-=&&=^^)", {OpMinusSet, OpLogicAndSet, OpLogicXor});
TEST_CASE(Operator, Permute, 75, R"(>>>=>>=../)", {OpROTRSet, OpRShiftSet, OpRange, OpSlash});
TEST_CASE(Operator, Permute, 76, R"(-=&&^^=...)", {OpMinusSet, OpLogicAnd, OpLogicXorSet, OpEllipsis});
TEST_CASE(Operator, Permute, 77, R"(++?^^>>>)", {OpInc, OpTernary, OpLogicXor, OpROTR});
TEST_CASE(Operator, Permute, 78, R"(%^^=&&^=)", {OpPercent, OpLogicXorSet, OpLogicAnd, OpBitXorSet});
TEST_CASE(Operator, Permute, 79, R"(>=..>-)", {OpGE, OpRange, OpGT, OpMinus});
TEST_CASE(Operator, Permute, 80, R"(>>=%=/===)", {OpRShiftSet, OpPercentSet, OpSlashSet, OpEq});
TEST_CASE(Operator, Permute, 81, R"(<<<=.==^=)", {OpROTLSet, OpDot, OpEq, OpBitXorSet});
TEST_CASE(Operator, Permute, 82, R"(>|=^^=~)", {OpGT, OpBitOrSet, OpLogicXorSet, OpBitNot});
TEST_CASE(Operator, Permute, 83, R"(>>>><<..)", {OpROTR, OpGT, OpLShift, OpRange});
TEST_CASE(Operator, Permute, 84, R"(...=+==>)", {OpEllipsis, OpSet, OpPlusSet, OpArrow});
TEST_CASE(Operator, Permute, 85, R"(&=---/)", {OpBitAndSet, OpDec, OpMinus, OpSlash});
TEST_CASE(Operator, Permute, 86, R"(+|++!)", {OpPlus, OpBitOr, OpInc, OpLogicNot});
TEST_CASE(Operator, Permute, 87, R"(!&&=<<<=&&)", {OpLogicNot, OpLogicAndSet, OpROTLSet, OpLogicAnd});
TEST_CASE(Operator, Permute, 88, R"(<=&&=<<<<<)", {OpLE, OpLogicAndSet, OpROTL, OpLShift});
TEST_CASE(Operator, Permute, 89, R"(^--^^=>>)", {OpBitXor, OpDec, OpLogicXorSet, OpRShift});
TEST_CASE(Operator, Permute, 90, R"(--^<=<<)", {OpDec, OpBitXor, OpLE, OpLShift});
TEST_CASE(Operator, Permute, 91, R"(>>>=-=+=>>)", {OpROTRSet, OpMinusSet, OpPlusSet, OpRShift});
TEST_CASE(Operator, Permute, 92, R"(*--!<)", {OpTimes, OpDec, OpLogicNot, OpLT});
TEST_CASE(Operator, Permute, 93, R"(<&->>=)", {OpLT, OpBitAnd, OpMinus, OpRShiftSet});
TEST_CASE(Operator, Permute, 94, R"(&/===^^=)", {OpBitAnd, OpSlashSet, OpEq, OpLogicXorSet});
TEST_CASE(Operator, Permute, 95, R"(>=>>=?>>>=)", {OpGE, OpRShiftSet, OpTernary, OpROTRSet});
TEST_CASE(Operator, Permute, 96, R"(<||<<-)", {OpLT, OpLogicOr, OpLShift, OpMinus});
TEST_CASE(Operator, Permute, 97, R"(+=^^<=/)", {OpPlusSet, OpLogicXor, OpLE, OpSlash});
TEST_CASE(Operator, Permute, 98, R"(|=>&=~)", {OpBitOrSet, OpGT, OpBitAndSet, OpBitNot});
TEST_CASE(Operator, Permute, 99, R"(>>||&&=%)", {OpRShift, OpLogicOr, OpLogicAndSet, OpPercent});
TEST_CASE(Operator, Permute, 100, R"(>>>-=^^^^=)", {OpROTR, OpMinusSet, OpLogicXor, OpLogicXorSet});
TEST_CASE(Operator, Permute, 101, R"(||=!/=>=)", {OpLogicOrSet, OpLogicNot, OpSlashSet, OpGE});
TEST_CASE(Operator, Permute, 102, R"(||=>=?--)", {OpLogicOrSet, OpGE, OpTernary, OpDec});
TEST_CASE(Operator, Permute, 103, R"(!&==>>>)", {OpLogicNot, OpBitAndSet, OpArrow, OpRShift});
TEST_CASE(Operator, Permute, 104, R"(*&=<=<<<)", {OpTimes, OpBitAndSet, OpLE, OpROTL});
TEST_CASE(Operator, Permute, 105, R"(%->>>=*=)", {OpPercent, OpMinus, OpROTRSet, OpTimesSet});
TEST_CASE(Operator, Permute, 106, R"(>>|=%===)", {OpRShift, OpBitOrSet, OpPercentSet, OpEq});
TEST_CASE(Operator, Permute, 107, R"(=<<=+=>>>=)", {OpSet, OpLShiftSet, OpPlusSet, OpROTRSet});
TEST_CASE(Operator, Permute, 108, R"(/<<=<<^=)", {OpSlash, OpLShiftSet, OpLShift, OpBitXorSet});
TEST_CASE(Operator, Permute, 109, R"(-=*!~)", {OpMinusSet, OpTimes, OpLogicNot, OpBitNot});
TEST_CASE(Operator, Permute, 110, R"(^=...%=>>=)", {OpBitXorSet, OpEllipsis, OpPercentSet, OpRShiftSet});
TEST_CASE(Operator, Permute, 111, R"(%!=+=|)", {OpPercent, OpNE, OpPlusSet, OpBitOr});
TEST_CASE(Operator, Permute, 112, R"(>>>!=>>=/=)", {OpROTR, OpNE, OpRShiftSet, OpSlashSet});
TEST_CASE(Operator, Permute, 113, R"(++||=&&...)", {OpInc, OpLogicOrSet, OpLogicAnd, OpEllipsis});
TEST_CASE(Operator, Permute, 114, R"(-&--/=)", {OpMinus, OpBitAnd, OpDec, OpSlashSet});
TEST_CASE(Operator, Permute, 115, R"(<<=-=++^^)", {OpLShiftSet, OpMinusSet, OpInc, OpLogicXor});
TEST_CASE(Operator, Permute, 116, R"(>^=&==)", {OpGT, OpBitXorSet, OpBitAndSet, OpSet});
TEST_CASE(Operator, Permute, 117, R"(-!&...)", {OpMinus, OpLogicNot, OpBitAnd, OpEllipsis});
TEST_CASE(Operator, Permute, 118, R"(^^...|<<<=)", {OpLogicXor, OpEllipsis, OpBitOr, OpROTLSet});
TEST_CASE(Operator, Permute, 119, R"(<>..&&)", {OpLT, OpGT, OpRange, OpLogicAnd});
TEST_CASE(Operator, Permute, 120, R"(!=>>>=>>>=>)", {OpNE, OpROTRSet, OpROTRSet, OpGT});
TEST_CASE(Operator, Permute, 121, R"(&&<<^=>>=)", {OpLogicAnd, OpLShift, OpBitXorSet, OpRShiftSet});
TEST_CASE(Operator, Permute, 122, R"(||&&||==>)", {OpLogicOr, OpLogicAnd, OpLogicOrSet, OpArrow});
TEST_CASE(Operator, Permute, 123, R"(+>>>&|)", {OpPlus, OpROTR, OpBitAnd, OpBitOr});
TEST_CASE(Operator, Permute, 124, R"(!=>..||)", {OpNE, OpGT, OpRange, OpLogicOr});
TEST_CASE(Operator, Permute, 125, R"(||=>>>?)", {OpLogicOrSet, OpROTR, OpTernary});
TEST_CASE(Operator, Permute, 126, R"(&=>>-=>)", {OpBitAndSet, OpRShift, OpMinusSet, OpGT});
TEST_CASE(Operator, Permute, 127, R"(||=^^>=<<)", {OpLogicOrSet, OpLogicXor, OpGE, OpLShift});
TEST_CASE(Operator, Permute, 128, R"(++<<<=>?)", {OpInc, OpROTLSet, OpGT, OpTernary});
TEST_CASE(Operator, Permute, 129, R"(=&..%)", {OpSet, OpBitAnd, OpRange, OpPercent});
TEST_CASE(Operator, Permute, 130, R"(<<^^--*)", {OpLShift, OpLogicXor, OpDec, OpTimes});
TEST_CASE(Operator, Permute, 131, R"(~...>>>=>)", {OpBitNot, OpEllipsis, OpROTRSet, OpGT});
TEST_CASE(Operator, Permute, 132, R"(==<<<=|++)", {OpEq, OpROTLSet, OpBitOr, OpInc});
TEST_CASE(Operator, Permute, 133, R"(>>>=>>=!/)", {OpROTRSet, OpRShiftSet, OpLogicNot, OpSlash});
TEST_CASE(Operator, Permute, 134, R"(&&=|||=%=)", {OpLogicAndSet, OpLogicOr, OpBitOrSet, OpPercentSet});
TEST_CASE(Operator, Permute, 135, R"(+=*=^|)", {OpPlusSet, OpTimesSet, OpBitXor, OpBitOr});
TEST_CASE(Operator, Permute, 136, R"(>>>=<<>>>!)", {OpROTRSet, OpLShift, OpROTR, OpLogicNot});
TEST_CASE(Operator, Permute, 137, R"(..--<!=)", {OpRange, OpDec, OpLT, OpNE});
TEST_CASE(Operator, Permute, 138, R"(||->=--)", {OpLogicOr, OpMinus, OpGE, OpDec});
TEST_CASE(Operator, Permute, 139, R"(|=*=^===)", {OpBitOrSet, OpTimesSet, OpBitXorSet, OpEq});
TEST_CASE(Operator, Permute, 140, R"(+~<<<>=)", {OpPlus, OpBitNot, OpROTL, OpGE});
TEST_CASE(Operator, Permute, 141, R"(<<<>>=^^=-)", {OpROTL, OpRShiftSet, OpLogicXorSet, OpMinus});
TEST_CASE(Operator, Permute, 142, R"(%=^^=...>>)", {OpPercentSet, OpLogicXorSet, OpEllipsis, OpRShift});
TEST_CASE(Operator, Permute, 143, R"(%>>>^=|=)", {OpPercent, OpROTR, OpBitXorSet, OpBitOrSet});
TEST_CASE(Operator, Permute, 144, R"(++||=||*)", {OpInc, OpLogicOrSet, OpLogicOr, OpTimes});
TEST_CASE(Operator, Permute, 145, R"(&&|=>>>^)", {OpLogicAnd, OpBitOrSet, OpROTR, OpBitXor});
TEST_CASE(Operator, Permute, 146, R"(...++%=~)", {OpEllipsis, OpInc, OpPercentSet, OpBitNot});
TEST_CASE(Operator, Permute, 147, R"(||=>==>>=)", {OpLogicOrSet, OpGE, OpArrow, OpGE});
TEST_CASE(Operator, Permute, 148, R"(~<=>>>=)", {OpBitNot, OpLE, OpROTRSet});
TEST_CASE(Operator, Permute, 149, R"(-<<<=&<<=)", {OpMinus, OpROTLSet, OpBitAnd, OpLShiftSet});
TEST_CASE(Operator, Permute, 150, R"(-!=%=)", {OpMinus, OpNE, OpPercentSet});
TEST_CASE(Operator, Permute, 151, R"(<<<=>==>)", {OpROTLSet, OpGE, OpArrow});
TEST_CASE(Operator, Permute, 152, R"(^<=^^=...)", {OpBitXor, OpLE, OpLogicXorSet, OpEllipsis});
TEST_CASE(Operator, Permute, 153, R"(^<~&&=)", {OpBitXor, OpLT, OpBitNot, OpLogicAndSet});
TEST_CASE(Operator, Permute, 154, R"(&&=?~/=)", {OpLogicAndSet, OpTernary, OpBitNot, OpSlashSet});
TEST_CASE(Operator, Permute, 155, R"(%=>>!=>)", {OpPercentSet, OpRShift, OpNE, OpGT});
TEST_CASE(Operator, Permute, 156, R"(<<==>=>>>)", {OpLShiftSet, OpArrow, OpArrow, OpRShift});
TEST_CASE(Operator, Permute, 157, R"(<<<=&>>>=/)", {OpROTLSet, OpBitAnd, OpROTRSet, OpSlash});
TEST_CASE(Operator, Permute, 158, R"(=>/=*=>=)", {OpArrow, OpSlashSet, OpTimesSet, OpGE});
TEST_CASE(Operator, Permute, 159, R"(||?.&)", {OpLogicOr, OpTernary, OpDot, OpBitAnd});
TEST_CASE(Operator, Permute, 160, R"(<<<=~...%)", {OpROTLSet, OpBitNot, OpEllipsis, OpPercent});
TEST_CASE(Operator, Permute, 161, R"(>>=>%<<<)", {OpRShiftSet, OpGT, OpPercent, OpROTL});
TEST_CASE(Operator, Permute, 162, R"(>...+=-)", {OpGT, OpEllipsis, OpPlusSet, OpMinus});
TEST_CASE(Operator, Permute, 163, R"(%=++<*=)", {OpPercentSet, OpInc, OpLT, OpTimesSet});
TEST_CASE(Operator, Permute, 164, R"(/>=>>===)", {OpSlash, OpGE, OpRShiftSet, OpEq});
TEST_CASE(Operator, Permute, 165, R"(&&/|=?)", {OpLogicAnd, OpSlash, OpBitOrSet, OpTernary});
TEST_CASE(Operator, Permute, 166, R"(>>>^^-=>)", {OpROTR, OpLogicXor, OpMinusSet, OpGT});
TEST_CASE(Operator, Permute, 167, R"(-=<<=+=%=)", {OpMinusSet, OpLShiftSet, OpPlusSet, OpPercentSet});
TEST_CASE(Operator, Permute, 168, R"(<||!==)", {OpLT, OpLogicOr, OpNE, OpSet});
TEST_CASE(Operator, Permute, 169, R"(>>=^=++*=)", {OpRShiftSet, OpBitXorSet, OpInc, OpTimesSet});
TEST_CASE(Operator, Permute, 170, R"(*=<<=++...)", {OpTimesSet, OpLShiftSet, OpInc, OpEllipsis});
TEST_CASE(Operator, Permute, 171, R"(<=><<<=!=)", {OpLE, OpGT, OpROTLSet, OpNE});
TEST_CASE(Operator, Permute, 172, R"(^^=||=-->>>)", {OpLogicXorSet, OpLogicOrSet, OpDec, OpROTR});
TEST_CASE(Operator, Permute, 173, R"(...*+=<<=)", {OpEllipsis, OpTimes, OpPlusSet, OpLShiftSet});
TEST_CASE(Operator, Permute, 174, R"(>>>=>>==^^=)", {OpROTRSet, OpRShiftSet, OpSet, OpLogicXorSet});
TEST_CASE(Operator, Permute, 175, R"(<<=&&^^=?)", {OpLShiftSet, OpLogicAnd, OpLogicXorSet, OpTernary});
TEST_CASE(Operator, Permute, 176, R"(*/=%)", {OpTimes, OpSlashSet, OpPercent});
TEST_CASE(Operator, Permute, 177, R"(&&+=^^~)", {OpLogicAnd, OpPlusSet, OpLogicXor, OpBitNot});
TEST_CASE(Operator, Permute, 178, R"(--=<=/)", {OpDec, OpSet, OpLE, OpSlash});
TEST_CASE(Operator, Permute, 179, R"(<<--&&%=)", {OpLShift, OpDec, OpLogicAnd, OpPercentSet});
TEST_CASE(Operator, Permute, 180, R"(*?^^=>>>=)", {OpTimes, OpTernary, OpLogicXorSet, OpROTRSet});
TEST_CASE(Operator, Permute, 181, R"(^^=*=*||=)", {OpLogicXorSet, OpTimesSet, OpTimes, OpLogicOrSet});
TEST_CASE(Operator, Permute, 182, R"(=>|*-=)", {OpArrow, OpBitOr, OpTimes, OpMinusSet});
TEST_CASE(Operator, Permute, 183, R"(+!=...^^=)", {OpPlus, OpNE, OpEllipsis, OpLogicXorSet});
TEST_CASE(Operator, Permute, 184, R"(!=>=++<)", {OpNE, OpGE, OpInc, OpLT});
TEST_CASE(Operator, Permute, 185, R"(|<<<=&&==>)", {OpBitOr, OpROTLSet, OpLogicAndSet, OpArrow});
TEST_CASE(Operator, Permute, 186, R"(^^=>>>./=)", {OpLogicXorSet, OpROTR, OpDot, OpSlashSet});
TEST_CASE(Operator, Permute, 187, R"(..<=/-)", {OpRange, OpLE, OpSlash, OpMinus});
TEST_CASE(Operator, Permute, 188, R"(+=&=<)", {OpPlusSet, OpBitAndSet, OpLT});
TEST_CASE(Operator, Permute, 189, R"(<<%=~|)", {OpLShift, OpPercentSet, OpBitNot, OpBitOr});
TEST_CASE(Operator, Permute, 190, R"(<<=&&=.*=)", {OpLShiftSet, OpLogicAndSet, OpDot, OpTimesSet});
TEST_CASE(Operator, Permute, 191, R"(!/>><)", {OpLogicNot, OpSlash, OpRShift, OpLT});
TEST_CASE(Operator, Permute, 192, R"(^>>>>>...)", {OpBitXor, OpROTR, OpRShift, OpEllipsis});
TEST_CASE(Operator, Permute, 193, R"(--|=%%=)", {OpDec, OpBitOrSet, OpPercent, OpPercentSet});
TEST_CASE(Operator, Permute, 194, R"(^=..>>=>>>)", {OpBitXorSet, OpRange, OpRShiftSet, OpROTR});
TEST_CASE(Operator, Permute, 195, R"(%=.!=+=)", {OpPercentSet, OpDot, OpNE, OpPlusSet});
TEST_CASE(Operator, Permute, 196, R"(<<<=&&===>=)", {OpROTLSet, OpLogicAndSet, OpEq, OpGE});
TEST_CASE(Operator, Permute, 197, R"(-=<<<=<<=)", {OpMinusSet, OpROTLSet, OpLShiftSet});
TEST_CASE(Operator, Permute, 198, R"(*>>?<)", {OpTimes, OpRShift, OpTernary, OpLT});
TEST_CASE(Operator, Permute, 199, R"(>>>|!=<<<)", {OpROTR, OpBitOr, OpNE, OpROTL});
TEST_CASE(Operator, Permute, 200, R"(<<=^=/=||)", {OpLShiftSet, OpBitXorSet, OpSlashSet, OpLogicOr});
TEST_CASE(Operator, Permute, 201, R"(*^=>>!=)", {OpTimes, OpBitXorSet, OpRShift, OpNE});
TEST_CASE(Operator, Permute, 202, R"(+=%=>>>>)", {OpPlusSet, OpPercentSet, OpROTR, OpGT});
TEST_CASE(Operator, Permute, 203, R"(+=%<<<=/)", {OpPlusSet, OpPercent, OpROTLSet, OpSlash});
TEST_CASE(Operator, Permute, 204, R"(&=<<^^=|=)", {OpBitAndSet, OpLShift, OpLogicXorSet, OpBitOrSet});
TEST_CASE(Operator, Permute, 205, R"(%=...*>=)", {OpPercentSet, OpEllipsis, OpTimes, OpGE});
TEST_CASE(Operator, Permute, 206, R"(+=<=..=)", {OpPlusSet, OpLE, OpRange, OpSet});
TEST_CASE(Operator, Permute, 207, R"(..?|&&)", {OpRange, OpTernary, OpBitOr, OpLogicAnd});
TEST_CASE(Operator, Permute, 208, R"(>>>=...?>)", {OpROTRSet, OpEllipsis, OpTernary, OpGT});
TEST_CASE(Operator, Permute, 209, R"(...>-<<<)", {OpEllipsis, OpGT, OpMinus, OpROTL});
TEST_CASE(Operator, Permute, 210, R"(<<<=||+!=)", {OpROTLSet, OpLogicOr, OpPlus, OpNE});
TEST_CASE(Operator, Permute, 211, R"(>>><<<&=*=)", {OpROTR, OpROTL, OpBitAndSet, OpTimesSet});
TEST_CASE(Operator, Permute, 212, R"(++|=...)", {OpInc, OpBitOrSet, OpEllipsis});
TEST_CASE(Operator, Permute, 213, R"(...^*>)", {OpEllipsis, OpBitXor, OpTimes, OpGT});
TEST_CASE(Operator, Permute, 214, R"(%==.*)", {OpPercentSet, OpSet, OpDot, OpTimes});
TEST_CASE(Operator, Permute, 215, R"(^^/=<<<!)", {OpLogicXor, OpSlashSet, OpROTL, OpLogicNot});
TEST_CASE(Operator, Permute, 216, R"(?<&=^)", {OpTernary, OpLT, OpBitAndSet, OpBitXor});
TEST_CASE(Operator, Permute, 217, R"(>>>=&&=!=&&)", {OpROTRSet, OpLogicAndSet, OpNE, OpLogicAnd});
TEST_CASE(Operator, Permute, 218, R"(>>=^>>+=)", {OpRShiftSet, OpBitXor, OpRShift, OpPlusSet});
TEST_CASE(Operator, Permute, 219, R"(>>>=^=<<<===)", {OpROTRSet, OpBitXorSet, OpROTLSet, OpEq});
TEST_CASE(Operator, Permute, 220, R"(*=...>=>)", {OpTimesSet, OpEllipsis, OpGE, OpGT});
TEST_CASE(Operator, Permute, 221, R"(+=-=...==)", {OpPlusSet, OpMinusSet, OpEllipsis, OpEq});
TEST_CASE(Operator, Permute, 222, R"(=>^^!=/=)", {OpArrow, OpLogicXor, OpNE, OpSlashSet});
TEST_CASE(Operator, Permute, 223, R"(|--===)", {OpBitOr, OpDec, OpEq, OpSet});
TEST_CASE(Operator, Permute, 224, R"(~^^=<=&)", {OpBitNot, OpLogicXorSet, OpLE, OpBitAnd});
TEST_CASE(Operator, Permute, 225, R"(<<<|..?)", {OpROTL, OpBitOr, OpRange, OpTernary});
TEST_CASE(Operator, Permute, 226, R"(|<=<<>=)", {OpBitOr, OpLE, OpLShift, OpGE});
TEST_CASE(Operator, Permute, 227, R"(/^^&===)", {OpSlash, OpLogicXor, OpBitAndSet, OpEq});
TEST_CASE(Operator, Permute, 228, R"(&/=^^=<=)", {OpBitAnd, OpSlashSet, OpLogicXorSet, OpLE});
TEST_CASE(Operator, Permute, 229, R"(...<<--&&)", {OpEllipsis, OpLShift, OpDec, OpLogicAnd});
TEST_CASE(Operator, Permute, 230, R"(||=<<<=>>==>)", {OpLogicOrSet, OpROTLSet, OpRShiftSet, OpArrow});
TEST_CASE(Operator, Permute, 231, R"(-^*=<)", {OpMinus, OpBitXor, OpTimesSet, OpLT});
TEST_CASE(Operator, Permute, 232, R"(%...^^=.)", {OpPercent, OpEllipsis, OpLogicXorSet, OpDot});
TEST_CASE(Operator, Permute, 233, R"(&=||=/=)", {OpBitAndSet, OpLogicOrSet, OpSlashSet});
TEST_CASE(Operator, Permute, 234, R"(>=^<=<<<)", {OpGE, OpBitXor, OpLE, OpROTL});
TEST_CASE(Operator, Permute, 235, R"(&&^^=&&=%=)", {OpLogicAnd, OpLogicXorSet, OpLogicAndSet, OpPercentSet});
TEST_CASE(Operator, Permute, 236, R"(<<</=-%)", {OpROTL, OpSlashSet, OpMinus, OpPercent});
TEST_CASE(Operator, Permute, 237, R"(&&<<=++!)", {OpLogicAnd, OpLShiftSet, OpInc, OpLogicNot});
TEST_CASE(Operator, Permute, 238, R"(&&-=/=>=)", {OpLogicAnd, OpMinusSet, OpSlashSet, OpGE});
TEST_CASE(Operator, Permute, 239, R"(^>>>-->>=)", {OpBitXor, OpROTR, OpDec, OpRShiftSet});
TEST_CASE(Operator, Permute, 240, R"(>%<-=)", {OpGT, OpPercent, OpLT, OpMinusSet});
TEST_CASE(Operator, Permute, 241, R"(||...>>^=)", {OpLogicOr, OpEllipsis, OpRShift, OpBitXorSet});
TEST_CASE(Operator, Permute, 242, R"(++!=&&=--)", {OpInc, OpNE, OpLogicAndSet, OpDec});
TEST_CASE(Operator, Permute, 243, R"(>>>==&&||=)", {OpROTRSet, OpSet, OpLogicAnd, OpLogicOrSet});
TEST_CASE(Operator, Permute, 244, R"(<<=&=.>>=)", {OpLShiftSet, OpBitAndSet, OpDot, OpRShiftSet});
TEST_CASE(Operator, Permute, 245, R"(==&/*)", {OpEq, OpBitAnd});
TEST_CASE(Operator, Permute, 246, R"(+--^^=*)", {OpPlus, OpDec, OpLogicXorSet, OpTimes});
TEST_CASE(Operator, Permute, 247, R"(!...>>>=--)", {OpLogicNot, OpEllipsis, OpROTRSet, OpDec});
TEST_CASE(Operator, Permute, 248, R"(||=>>>=>><=)", {OpLogicOrSet, OpROTRSet, OpRShift, OpLE});
TEST_CASE(Operator, Permute, 249, R"(==--*+)", {OpEq, OpDec, OpTimes, OpPlus});
TEST_CASE(Operator, Permute, 250, R"(>=--%<<<=)", {OpGE, OpDec, OpPercent, OpROTLSet});
TEST_CASE(Operator, Permute, 251, R"(~+=||=<<<)", {OpBitNot, OpPlusSet, OpLogicOrSet, OpROTL});
TEST_CASE(Operator, Permute, 252, R"(-!...<<=)", {OpMinus, OpLogicNot, OpEllipsis, OpLShiftSet});
TEST_CASE(Operator, Permute, 253, R"(-->*=&)", {OpDec, OpGT, OpTimesSet, OpBitAnd});
TEST_CASE(Operator, Permute, 254, R"(||=<<=>>>==)", {OpLogicOrSet, OpLShiftSet, OpROTRSet, OpSet});
TEST_CASE(Operator, Permute, 255, R"(=/>>>>>>=)", {OpSet, OpSlash, OpROTR, OpROTRSet});
TEST_CASE(Operator, Permute, 256, R"(||<=<<<--)", {OpLogicOr, OpLE, OpROTL, OpDec});
TEST_CASE(Operator, Permute, 257, R"(--=>=>>>)", {OpDec, OpArrow, OpArrow, OpRShift});
TEST_CASE(Operator, Permute, 258, R"(<-&--)", {OpLT, OpMinus, OpBitAnd, OpDec});
TEST_CASE(Operator, Permute, 259, R"(|=*<<=|)", {OpBitOrSet, OpTimes, OpLShiftSet, OpBitOr});
TEST_CASE(Operator, Permute, 260, R"(>>-<<<^=)", {OpRShift, OpMinus, OpROTL, OpBitXorSet});
TEST_CASE(Operator, Permute, 261, R"(>>=%=<<<=+)", {OpRShiftSet, OpPercentSet, OpROTLSet, OpPlus});
TEST_CASE(Operator, Permute, 262, R"(%~/=*)", {OpPercent, OpBitNot, OpSlashSet, OpTimes});
TEST_CASE(Operator, Permute, 263, R"(*><<<<)", {OpTimes, OpGT, OpROTL, OpLT});
TEST_CASE(Operator, Permute, 264, R"(^=...+*=)", {OpBitXorSet, OpEllipsis, OpPlus, OpTimesSet});
TEST_CASE(Operator, Permute, 265, R"(|<<<<||)", {OpBitOr, OpROTL, OpLT, OpLogicOr});
TEST_CASE(Operator, Permute, 266, R"(*===&<<<=)", {OpTimesSet, OpEq, OpBitAnd, OpROTLSet});
TEST_CASE(Operator, Permute, 267, R"(<=||^--)", {OpLE, OpLogicOr, OpBitXor, OpDec});
TEST_CASE(Operator, Permute, 268, R"(^=>=>>>==>)", {OpBitXorSet, OpGE, OpROTRSet, OpArrow});
TEST_CASE(Operator, Permute, 269, R"(||=*=^^<<=)", {OpLogicOrSet, OpTimesSet, OpLogicXor, OpLShiftSet});
TEST_CASE(Operator, Permute, 270, R"(^..&&%=)", {OpBitXor, OpRange, OpLogicAnd, OpPercentSet});
TEST_CASE(Operator, Permute, 271, R"(>>>====>>=)", {OpROTRSet, OpEq, OpArrow, OpGE});
TEST_CASE(Operator, Permute, 272, R"(/&&=+=/=)", {OpSlash, OpLogicAndSet, OpPlusSet, OpSlashSet});
TEST_CASE(Operator, Permute, 273, R"(^=/&&--)", {OpBitXorSet, OpSlash, OpLogicAnd, OpDec});
TEST_CASE(Operator, Permute, 274, R"(>~&&<<=)", {OpGT, OpBitNot, OpLogicAnd, OpLShiftSet});
TEST_CASE(Operator, Permute, 275, R"(==<<<<<=...)", {OpEq, OpROTL, OpLShiftSet, OpEllipsis});
TEST_CASE(Operator, Permute, 276, R"(*!=%=*=)", {OpTimes, OpNE, OpPercentSet, OpTimesSet});
TEST_CASE(Operator, Permute, 277, R"(%=^=<<<=>)", {OpPercentSet, OpBitXorSet, OpROTLSet, OpGT});
TEST_CASE(Operator, Permute, 278, R"(>>&=<~)", {OpRShift, OpBitAndSet, OpLT, OpBitNot});
TEST_CASE(Operator, Permute, 279, R"(<<=!||=/=)", {OpLShiftSet, OpLogicNot, OpLogicOrSet, OpSlashSet});
TEST_CASE(Operator, Permute, 280, R"(+=>=>>>||)", {OpPlusSet, OpGE, OpROTR, OpLogicOr});
TEST_CASE(Operator, Permute, 281, R"(...<=<<&=)", {OpEllipsis, OpLE, OpLShift, OpBitAndSet});
TEST_CASE(Operator, Permute, 282, R"(+&&|=!=)", {OpPlus, OpLogicAnd, OpBitOrSet, OpNE});
TEST_CASE(Operator, Permute, 283, R"(&&>><~)", {OpLogicAnd, OpRShift, OpLT, OpBitNot});
TEST_CASE(Operator, Permute, 284, R"(>>>^=|=&=)", {OpROTR, OpBitXorSet, OpBitOrSet, OpBitAndSet});
TEST_CASE(Operator, Permute, 285, R"(++>>>=|/)", {OpInc, OpROTRSet, OpBitOr, OpSlash});
TEST_CASE(Operator, Permute, 286, R"(<<<<-<<<=)", {OpROTL, OpLT, OpMinus, OpROTLSet});
TEST_CASE(Operator, Permute, 287, R"(^=^^=&&<<<)", {OpBitXorSet, OpLogicXorSet, OpLogicAnd, OpROTL});
TEST_CASE(Operator, Permute, 288, R"(<<=<<<%=+)", {OpLShiftSet, OpROTL, OpPercentSet, OpPlus});
TEST_CASE(Operator, Permute, 289, R"(^^<</++)", {OpLogicXor, OpLShift, OpSlash, OpInc});
TEST_CASE(Operator, Permute, 290, R"(<<<^&*)", {OpROTL, OpBitXor, OpBitAnd, OpTimes});
TEST_CASE(Operator, Permute, 291, R"(&&=^&=%)", {OpLogicAndSet, OpBitXor, OpBitAndSet, OpPercent});
TEST_CASE(Operator, Permute, 292, R"(-+=/++)", {OpMinus, OpPlusSet, OpSlash, OpInc});
TEST_CASE(Operator, Permute, 293, R"(..&=<<%=)", {OpRange, OpBitAndSet, OpLShift, OpPercentSet});
TEST_CASE(Operator, Permute, 294, R"(^<<<=>>=)", {OpBitXor, OpROTLSet, OpRShiftSet});
TEST_CASE(Operator, Permute, 295, R"(.<>>>=%)", {OpDot, OpLT, OpROTRSet, OpPercent});
TEST_CASE(Operator, Permute, 296, R"(!=<<=...*)", {OpNE, OpLShiftSet, OpEllipsis, OpTimes});
TEST_CASE(Operator, Permute, 297, R"(===>>=--)", {OpEq, OpArrow, OpGE, OpDec});
TEST_CASE(Operator, Permute, 298, R"(^^=<=>>>=!=)", {OpLogicXorSet, OpLE, OpROTRSet, OpNE});
TEST_CASE(Operator, Permute, 299, R"(<=<<<||=<)", {OpLE, OpROTL, OpLogicOrSet, OpLT});
TEST_CASE(Operator, Permute, 300, R"(++&&=-=+=)", {OpInc, OpLogicAndSet, OpMinusSet, OpPlusSet});

///=============================================================================
/// LEXICAL GARBAGE
TEST_CASE(Operator, Garbage, 0, R"($)", {});
TEST_CASE(Operator, Garbage, 1, R"(`)", {});
